
trigger:
- ci-fixes

jobs:
- job: Athanor
  timeoutInMinutes: 0
  strategy:
    matrix:
      Linux:
        imageName: 'ubuntu-latest'
        os: linux
        compiler: clang++
        conjureFolder: conjure-v2.3.0-linux-ubuntu1604
      Mac:
        imageName: 'macos-latest'
        os: mac
        compiler: clang++
        conjureFolder: conjure-v2.3.0-macos


  pool:
    vmImage: $(imageName)
  steps:
  - bash: CXX=$(compiler) make -j4
    displayName: "Build Athanor"
  - bash: rm -rf temp && mkdir temp && cd temp && wget https://github.com/conjure-cp/conjure/releases/download/v2.3.0/$(conjureFolder).zip && unzip $(conjureFolder).zip
    displayName: "Downloading Conjure"
  - bash: export PATH="$PWD/temp/$(conjureFolder):${PATH}" ; echo "path is $PATH" ; which conjure ; conjure ; cd tests && ./runAll.sh skipSanityCheck useReleaseBuild dumpFilesOnError
    displayName: "Running tests"
