
trigger:
- master

jobs:
- job: Athanor
  timeoutInMinutes: 0
  strategy:
    matrix:
      Linux:
        imageName: 'ubuntu-latest'
        os: linux
        compiler: clang++
      Mac:
        imageName: 'macos-latest'
        os: mac
        compiler: clang++


  pool:
    vmImage: $(imageName)
  steps:
  - bash: CXX=$(compiler) make
    displayName: "Build Athanor"
  - bash: echo In this step we download conjure for os $(os)
    displayName: "Download Conjure"
  - bash: echo Here we run the tests.
    displayName: "Run the tests"
