
trigger:
- master

jobs:
- job: Athanor
  timeoutInMinutes: 0
  strategy:
    matrix:
      Linux:
        imageName: 'ubuntu-latest'
        os: linux
        compiler: clang++
        conjureDownloadLink: https://github.com/conjure-cp/conjure/releases/download/v2.3.0/conjure-v2.3.0-linux.zip
      Mac:
        imageName: 'macos-latest'
        os: mac
        compiler: clang++
        conjureDownloadLink: https://github.com/conjure-cp/conjure/releases/download/v2.3.0/conjure-v2.3.0-mac.zip


  pool:
    vmImage: $(imageName)
  steps:
  - bash: CXX=$(compiler) make
    displayName: "Build Athanor"
  - bash: rm -rf temp && mkdir temp && cd temp && curl -O $(conjureDownloadLink)
    displayName: "Downloading Conjure"
  - bash: PATH="$PWD/temp:${PATH}" cd tests && ./runAll.sh skipSanityCheck useReleaseBuild dumpFilesOnError
    displayName: "Running tests"
