
trigger:
- master

jobs:
- job: Athanor
  timeoutInMinutes: 0
  strategy:
    matrix:
      Linux:
        imageName: 'ubuntu-latest'
        os: linux
      Mac:
        imageName: 'macos-latest'
        os: mac


  pool:
    vmImage: $(imageName)
  steps:
  - bash: make
    displayName: "Build Athanor"
  - bash: echo In this step we download conjure for os $(os)
    displayName: "Download Conjure"
  - bash: echo Here we run the tests.
    displayName: "Run the tests"
